export enum Genero {
  ActionRPG = "Action RPG",
  Arpg = "ARPG",
  BattleRoyale = "Battle Royale",
  Card = "Card",
  CardGame = "Card Game",
  Fantasy = "Fantasy",
  Fighting = "Fighting",
  GenreMMORPG = " MMORPG",
  GenreMOBA = "MOBA",
  MMORPG = "MMORPG",
  Mmo = "MMO",
  Mmoarpg = "MMOARPG",
  Moba = "Moba",
  Racing = "Racing",
  Shooter = "Shooter",
  Social = "Social",
  Sports = "Sports",
  Strategy = "Strategy",
}
